# Generated by Django 5.2.7 on 2025-11-03 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
    ]
